Document: televideo
Title: Debian televideo Manual
Author: <insert document author here>
Abstract: This manual describes what televideo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/televideo/televideo.sgml.gz

Format: postscript
Files: /usr/share/doc/televideo/televideo.ps.gz

Format: text
Files: /usr/share/doc/televideo/televideo.text.gz

Format: HTML
Index: /usr/share/doc/televideo/html/index.html
Files: /usr/share/doc/televideo/html/*.html
